title: Hackathon Demo
email: r.stropek@htl-leonding.ac.at
description: > # this means to ignore newlines until "baseurl:"
  Sharpen your coding skills in this hackathon.
url: "https://github-edu-workshop.github.io/jekyll-demo"
twitter_username: rstropek
github_username:  rstropek
baseurl: /jekyll-demo
